// This file is auto generated by the protocol-buffers compiler

/* eslint-disable quotes */
/* eslint-disable indent */
/* eslint-disable no-redeclare */
/* eslint-disable camelcase */

// Remember to `npm install --save protocol-buffers-encodings`
var encodings = require('protocol-buffers-encodings')
var varint = encodings.varint
var skip = encodings.skip

var ExtensionMessage = exports.ExtensionMessage = {
  buffer: true,
  encodingLength: null,
  encode: null,
  decode: null
}

defineExtensionMessage()

function defineExtensionMessage () {
  ExtensionMessage.encodingLength = encodingLength
  ExtensionMessage.encode = encode
  ExtensionMessage.decode = decode

  function encodingLength (obj) {
    var length = 0
    if (defined(obj.topicAlias)) {
      var len = encodings.varint.encodingLength(obj.topicAlias)
      length += 1 + len
    }
    if (defined(obj.topic)) {
      var len = encodings.bytes.encodingLength(obj.topic)
      length += 1 + len
    }
    if (defined(obj.msg)) {
      var len = encodings.bytes.encodingLength(obj.msg)
      length += 1 + len
    }
    return length
  }

  function encode (obj, buf, offset) {
    if (!offset) offset = 0
    if (!buf) buf = Buffer.allocUnsafe(encodingLength(obj))
    var oldOffset = offset
    if (defined(obj.topicAlias)) {
      buf[offset++] = 8
      encodings.varint.encode(obj.topicAlias, buf, offset)
      offset += encodings.varint.encode.bytes
    }
    if (defined(obj.topic)) {
      buf[offset++] = 18
      encodings.bytes.encode(obj.topic, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    if (defined(obj.msg)) {
      buf[offset++] = 26
      encodings.bytes.encode(obj.msg, buf, offset)
      offset += encodings.bytes.encode.bytes
    }
    encode.bytes = offset - oldOffset
    return buf
  }

  function decode (buf, offset, end) {
    if (!offset) offset = 0
    if (!end) end = buf.length
    if (!(end <= buf.length && offset <= buf.length)) throw new Error("Decoded message is not valid")
    var oldOffset = offset
    var obj = {
      topicAlias: 0,
      topic: null,
      msg: null
    }
    while (true) {
      if (end <= offset) {
        decode.bytes = offset - oldOffset
        return obj
      }
      var prefix = varint.decode(buf, offset)
      offset += varint.decode.bytes
      var tag = prefix >> 3
      switch (tag) {
        case 1:
        obj.topicAlias = encodings.varint.decode(buf, offset)
        offset += encodings.varint.decode.bytes
        break
        case 2:
        obj.topic = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        case 3:
        obj.msg = encodings.bytes.decode(buf, offset)
        offset += encodings.bytes.decode.bytes
        break
        default:
        offset = skip(prefix & 7, buf, offset)
      }
    }
  }
}

function defined (val) {
  return val !== null && val !== undefined && (typeof val !== 'number' || !isNaN(val))
}
